//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cd_proyectos
    {
        public int PROYECTOS_ID { get; set; }
        public string PROYECTOS_NOMBRE { get; set; }
        public string PROYECTOS_DESCRIPCION { get; set; }
        public string PROYECTOS_IMAGEN { get; set; }
        public Nullable<decimal> PROYECTOS_ORDEN { get; set; }
    }
}
